apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::036292124076:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-18T22:36:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: 9675
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 792bc933-dcd5-4b1d-a127-a175d2ea4f6f
